name: jadwal_sholat
description: Aplikasi sederhana untuk menampilkan jadwal sholat berdasarkan GPS.
version: 1.0.0+1
author: Mochamad Nizwar Syafuan
homepage: https://github.com/nizwar/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.1.3
  simplehttpconnection: ^1.3.0
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
  fonts:
    - family:  Logo
      fonts:
        - asset: assets/fonts/logo.ttf 